 notifications:
    slack: cg-codeguru:18tGNGNnfUzZzzhLQ5A4hvZb

language: java

jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: 6f12be4c-6765-4195-916c-340395cdffd3
  app: start-spring
 
