package com.javalec.dao;

import com.javalec.dto.MvcBoard;
import com.javalec.dto.MvcBoardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MvcBoardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvc_board
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    long countByExample(MvcBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvc_board
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    int deleteByExample(MvcBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvc_board
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    int deleteByPrimaryKey(Long bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvc_board
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    int insert(MvcBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvc_board
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    int insertSelective(MvcBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvc_board
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    List<MvcBoard> selectByExample(MvcBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvc_board
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    MvcBoard selectByPrimaryKey(Long bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvc_board
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    int updateByExampleSelective(@Param("record") MvcBoard record, @Param("example") MvcBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvc_board
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    int updateByExample(@Param("record") MvcBoard record, @Param("example") MvcBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvc_board
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    int updateByPrimaryKeySelective(MvcBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mvc_board
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    int updateByPrimaryKey(MvcBoard record);
}