package com.javalec.dto;

import java.util.Date;

public class MvcBoard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mvc_board.bId
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    private Long bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mvc_board.bName
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    private String bname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mvc_board.bTitle
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    private String btitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mvc_board.bContent
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    private String bcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mvc_board.bDate
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    private Date bdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mvc_board.bHit
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    private Integer bhit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mvc_board.bGroup
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    private Integer bgroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mvc_board.bStep
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    private Integer bstep;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mvc_board.bIndent
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    private Integer bindent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mvc_board.deleteFlag
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    private Integer deleteflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mvc_board.bId
     *
     * @return the value of mvc_board.bId
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    public Long getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mvc_board.bId
     *
     * @param bid the value for mvc_board.bId
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    public void setBid(Long bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mvc_board.bName
     *
     * @return the value of mvc_board.bName
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mvc_board.bName
     *
     * @param bname the value for mvc_board.bName
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    public void setBname(String bname) {
        this.bname = bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mvc_board.bTitle
     *
     * @return the value of mvc_board.bTitle
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    public String getBtitle() {
        return btitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mvc_board.bTitle
     *
     * @param btitle the value for mvc_board.bTitle
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    public void setBtitle(String btitle) {
        this.btitle = btitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mvc_board.bContent
     *
     * @return the value of mvc_board.bContent
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    public String getBcontent() {
        return bcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mvc_board.bContent
     *
     * @param bcontent the value for mvc_board.bContent
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    public void setBcontent(String bcontent) {
        this.bcontent = bcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mvc_board.bDate
     *
     * @return the value of mvc_board.bDate
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    public Date getBdate() {
        return bdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mvc_board.bDate
     *
     * @param bdate the value for mvc_board.bDate
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    public void setBdate(Date bdate) {
        this.bdate = bdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mvc_board.bHit
     *
     * @return the value of mvc_board.bHit
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    public Integer getBhit() {
        return bhit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mvc_board.bHit
     *
     * @param bhit the value for mvc_board.bHit
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    public void setBhit(Integer bhit) {
        this.bhit = bhit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mvc_board.bGroup
     *
     * @return the value of mvc_board.bGroup
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    public Integer getBgroup() {
        return bgroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mvc_board.bGroup
     *
     * @param bgroup the value for mvc_board.bGroup
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    public void setBgroup(Integer bgroup) {
        this.bgroup = bgroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mvc_board.bStep
     *
     * @return the value of mvc_board.bStep
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    public Integer getBstep() {
        return bstep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mvc_board.bStep
     *
     * @param bstep the value for mvc_board.bStep
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    public void setBstep(Integer bstep) {
        this.bstep = bstep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mvc_board.bIndent
     *
     * @return the value of mvc_board.bIndent
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    public Integer getBindent() {
        return bindent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mvc_board.bIndent
     *
     * @param bindent the value for mvc_board.bIndent
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    public void setBindent(Integer bindent) {
        this.bindent = bindent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mvc_board.deleteFlag
     *
     * @return the value of mvc_board.deleteFlag
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mvc_board.deleteFlag
     *
     * @param deleteflag the value for mvc_board.deleteFlag
     *
     * @mbg.generated Sat Dec 16 11:53:36 KST 2017
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
}